name: Build and Push Multi-Platform Docker Image

on:
  push:
    branches:
      - main
    tags:
      - "v*"

  workflow_dispatch:


env:
  IMAGE_NAME: huggingclip


jobs:
  docker:

    runs-on: ubuntu-latest


    permissions:
      contents: read
      packages: write


    steps:

      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4


      # Setup QEMU
      # 支持 arm64 构建
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3


      # Setup Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      # Login GHCR
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      # Docker metadata
      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:

          images: |
            ghcr.io/${{ github.repository_owner }}/huggingclip

          tags: |

            # latest
            type=raw,value=latest

            # git tag
            type=ref,event=tag

            # branch
            type=ref,event=branch

            # sha
            type=sha


      # Build and Push
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6

        with:

          context: .

          platforms: |
            linux/amd64
            linux/arm64

          push: true

          tags: |
            ${{ steps.meta.outputs.tags }}

          labels: |
            ${{ steps.meta.outputs.labels }}


          cache-from: |
            type=gha

          cache-to: |
            type=gha,mode=max
